"""Enumerations mirroring the values fixed by docs/ARCHITECTURE.md §2/§3 and
docs/API.md.  These strings cross the service boundary verbatim, so they must not
drift."""

from __future__ import annotations

from enum import StrEnum


class JobStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    IDENTIFYING_PRODUCT = "IDENTIFYING_PRODUCT"
    PLANNING_RESEARCH = "PLANNING_RESEARCH"
    RESEARCHING = "RESEARCHING"
    EXTRACTING_EVIDENCE = "EXTRACTING_EVIDENCE"
    ANALYZING = "ANALYZING"
    VERIFYING = "VERIFYING"
    GENERATING_REPORT = "GENERATING_REPORT"
    COMPLETED = "COMPLETED"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class EventType(StrEnum):
    PRODUCT_IDENTIFIED = "PRODUCT_IDENTIFIED"
    RESEARCH_STARTED = "RESEARCH_STARTED"
    WEB_RESEARCH_COMPLETED = "WEB_RESEARCH_COMPLETED"
    REDDIT_RESEARCH_COMPLETED = "REDDIT_RESEARCH_COMPLETED"
    YOUTUBE_RESEARCH_COMPLETED = "YOUTUBE_RESEARCH_COMPLETED"
    EVIDENCE_EXTRACTION_STARTED = "EVIDENCE_EXTRACTION_STARTED"
    EVIDENCE_EXTRACTION_COMPLETED = "EVIDENCE_EXTRACTION_COMPLETED"
    CLAIMS_GENERATED = "CLAIMS_GENERATED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    REPORT_GENERATION_STARTED = "REPORT_GENERATION_STARTED"
    REPORT_COMPLETED = "REPORT_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    JOB_PARTIALLY_COMPLETED = "JOB_PARTIALLY_COMPLETED"


class Channel(StrEnum):
    WEB = "WEB"
    REDDIT = "REDDIT"
    YOUTUBE = "YOUTUBE"


class SourceType(StrEnum):
    OFFICIAL_DOC = "OFFICIAL_DOC"
    PROFESSIONAL_REVIEW = "PROFESSIONAL_REVIEW"
    USER_EXPERIENCE = "USER_EXPERIENCE"
    FORUM_POST = "FORUM_POST"
    VIDEO_REVIEW = "VIDEO_REVIEW"
    GENERIC = "GENERIC"


class SourceStatus(StrEnum):
    FETCHED = "FETCHED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class Sentiment(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    MIXED = "MIXED"


class EvidenceType(StrEnum):
    FACT = "FACT"
    SPECIFICATION = "SPECIFICATION"
    EXPERT_OPINION = "EXPERT_OPINION"
    CUSTOMER_EXPERIENCE = "CUSTOMER_EXPERIENCE"
    REPEATED_PATTERN = "REPEATED_PATTERN"
    ANECDOTE = "ANECDOTE"
    COMPARISON = "COMPARISON"
    MEASUREMENT = "MEASUREMENT"
    CLAIM = "CLAIM"


class Strength(StrEnum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"


class ClaimStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    CONTESTED = "CONTESTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class Relationship(StrEnum):
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"
    CONTEXTUALIZES = "CONTEXTUALIZES"


class SectionType(StrEnum):
    EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY"
    CATEGORY_ANALYSIS = "CATEGORY_ANALYSIS"
    STRENGTHS = "STRENGTHS"
    WEAKNESSES = "WEAKNESSES"
    KEY_FINDINGS = "KEY_FINDINGS"
    COMMON_PRAISE = "COMMON_PRAISE"
    COMMON_COMPLAINTS = "COMMON_COMPLAINTS"
    CONFLICTS = "CONFLICTS"
    LONG_TERM_OWNERSHIP = "LONG_TERM_OWNERSHIP"
    WHO_SHOULD_BUY = "WHO_SHOULD_BUY"
    WHO_SHOULD_AVOID = "WHO_SHOULD_AVOID"
    CAVEATS = "CAVEATS"
    SOURCES = "SOURCES"


class ErrorCode(StrEnum):
    SOURCE_FAILURE = "SOURCE_FAILURE"
    AGENT_FAILURE = "AGENT_FAILURE"
    LLM_FAILURE = "LLM_FAILURE"
    TIMEOUT = "TIMEOUT"
    RATE_LIMIT = "RATE_LIMIT"
    INVALID_PRODUCT = "INVALID_PRODUCT"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
